spring:
  application:
    name: user
  rabbitmq:
    password: admin
    username: admin
    port: 5672
    host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
env: dev
girl: 
  name: huangyu
  sex: female
