spring:
  application:
    name: user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  rabbitmq:
    password: guest
    username: guest
    port: 5672
    host: localhost
env: dev
girl: 
  name: huangyu2
  sex: female
