spring:
  application:
    name: user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  rabbitmq:
    password: admin
    username: admin
    port: 5672
    host: localhost
env: dev
girl: 
  name: huangyu
  sex: female
